### ISSUE TITLE
[React] tweak design on an event card 

### ISSUE THREAD

**Issue by bluenex** [titipata/penn-events-calendar#19]
See temp demo at http://54.201.64.205/.

## TODOs

- [x] change cursor to `pointer` on the card when there is detail, only be pointer on `Collapse` area when expanded.
- [x] change `See Details` to `Collapse` when description is expanded, also change arrow direction
- [x] change onclick handler, only collapse when clicking on `Collapse` button
- [x] add URL to event, ~~only show when the detail is expanded~~ show next to event title because all have URL but not description -> open this URL in new tab on click
- [x] adjust spacing in description, the rendered just doesn't look good as seen in this card:
  - this is due to description is also HTML so it contains a lot of `&nbsp;` stuffs (see raw string below).

```txt
Fisher-Bennett Hall room TBD

V21: Victorian Studies for the 21st Century is sponsoring its fourth annual 
summer reading group series in 2018, with groups convening in multiple cities. 
&nbsp;Topics are “Work," “Blackness," and “Sex." &nbsp;The Philadelphia-area 
group will meet at Penn on&nbsp;June 21,&nbsp;July 19, and&nbsp;August 
16&nbsp;2-4pm.&nbsp;&nbsp;All are welcome!
```

![image](https://user-images.githubusercontent.com/11027706/42611044-5d3d79ea-85be-11e8-8fe6-7abf49413996.png)
