### ISSUE TITLE
[Frontend] UX enhancements

### ISSUE THREAD

**Issue by bluenex** [titipata/penn-events-calendar#52]
- [x] #62 ~~add pagination to a container, we should decide how many events should be shown per page~~
  - ~~https://www.gatsbyjs.org/docs/adding-pagination/~~
  - I think we should limit how many months we will show events instead
- [x] #71 sort event in each day by? (`starttime`, ~~`endtime`, `duration`, `title`~~)
- [x] #97 mplement responsive navbar (there should be a way to fix width of the logo image)
- [x] add loading indicator when switching from page to page
- [x] add feedback to interactive DOM like button and card (as mentioned in #20)
  - now we applied `keyframes` to some of the interactive DOMs
  - we can also add `transition` to some
  - this will need to be elaborated on which DOM to do, probably creating a new issue if we found something off
- [ ] ~add mini calendar so that user can navigate to each day~
  - https://www.gatsbyjs.org/docs/gatsby-link/#recommendations-for-programmatic-in-app-navigation
  - https://github.com/lelivrescolaire/react-light-calendar/pull/5
  - will open this up later if needed
